// This is a stub file. The actual types are generated by `npx convex dev`
// This allows the frontend to compile before running Convex

import React from 'react'

export type QueryBuilder<T> = {
  collect(): Promise<T[]>
  first(): Promise<T | null>
  order(field: string): QueryBuilder<T>
  filter(predicate: (q: any) => any): QueryBuilder<T>
  take(n: number): Promise<T[]>
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function useQuery(query: any, _args?: any): any {
  // In real usage, this is replaced by Convex's actual hook
  return undefined
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function useMutation(_mutation: any): any {
  // In real usage, this is replaced by Convex's actual hook
  // Return a function that returns a Promise to match real behavior
  return (_args?: any) => Promise.resolve({ _id: 'stub-user' })
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function useAction(_action: any): any {
  // In real usage, this is replaced by Convex's actual hook
  return (_args?: any) => Promise.resolve({})
}
