// AgentMail integration for session summaries
// API: https://agentmail.io/

interface SessionSummary {
  date: string
  workshopsExplored: string[]
  experimentsAttempted: number
  experimentsCompleted: number
  challengesSolved: string[]
  timeSpent: number // minutes
  discoveries: string[]
  nextSteps: string[]
}

export async function prepareSessionSummary(
  sessionData: SessionSummary
): Promise<{ subject: string; body: string; ready: boolean }> {
  const { workshopsExplored, experimentsAttempted, experimentsCompleted, challengesSolved, timeSpent, discoveries, nextSteps } = sessionData

  // Generate email content
  const subject = `Your Workshop Session - ${experimentsCompleted} experiments completed`

  const body = `
## Your Workshop Session

**Date:** ${sessionData.date}
**Time Spent:** ${timeSpent} minutes

### Workshops Explored
${workshopsExplored.length > 0
  ? workshopsExplored.map(w => `- ${w}`).join('\n')
  : '- None yet, start exploring!'}

### Experiments
- **Attempted:** ${experimentsAttempted}
- **Completed:** ${experimentsCompleted}
- **Success Rate:** ${experimentsAttempted > 0
    ? Math.round((experimentsCompleted / experimentsAttempted) * 100)
    : 0}%

### Challenges Solved
${challengesSolved.length > 0
  ? challengesSolved.map(c => `- ${c}`).join('\n')
  : '- No challenges completed yet'}

### Discoveries
${discoveries.length > 0
  ? discoveries.map(d => `- ${d}`).join('\n')
  : '- Keep experimenting to make discoveries!'}

### Suggested Next Steps
${nextSteps.length > 0
  ? nextSteps.map((n, i) => `${i + 1}. ${n}`).join('\n')
  : '- Try a new workshop or experiment with different approaches'}

---
*This summary was generated by Workshop - Learn by Experimenting*
`

  return {
    subject,
    body: body.trim(),
    ready: true,
  }
}

export async function sendApprovedSummary(
  summary: { subject: string; body: string },
  recipientEmail: string
): Promise<{ success: boolean; error?: string }> {
  const apiKey = import.meta.env.VITE_AGENTMAIL_API_KEY
  const inboxId = import.meta.env.VITE_AGENTMAIL_INBOX_ID

  if (!apiKey || !inboxId) {
    console.warn('AgentMail API not configured')
    return { success: false, error: 'AgentMail not configured' }
  }

  try {
    const response = await fetch('https://api.agentmail.io/v1/send', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        inboxId,
        to: recipientEmail,
        subject: summary.subject,
        body: summary.body,
        from: 'workshop@workshop.app',
      }),
    })

    if (!response.ok) {
      throw new Error(`AgentMail API error: ${response.status}`)
    }

    return { success: true }
  } catch (error) {
    console.error('AgentMail error:', error)
    return { success: false, error: String(error) }
  }
}

// Format time duration
export function formatDuration(minutes: number): string {
  if (minutes < 60) {
    return `${minutes}m`
  }
  const hours = Math.floor(minutes / 60)
  const mins = minutes % 60
  return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`
}

// Format relative time
export function formatRelativeTime(timestamp: number): string {
  const now = Date.now()
  const diff = now - timestamp

  const minutes = Math.floor(diff / 60000)
  const hours = Math.floor(diff / 3600000)
  const days = Math.floor(diff / 86400000)

  if (minutes < 1) return 'just now'
  if (minutes < 60) return `${minutes}m ago`
  if (hours < 24) return `${hours}h ago`
  if (days < 7) return `${days}d ago`

  return new Date(timestamp).toLocaleDateString()
}
